kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv%vol_nm%
  labels:
    type: aws
spec:
  capacity:
    storage: %vol_size%
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
   volumeID: %vol_nm%
   fsType: %fs_type%
---------------
